---
- name: Stage 1 - Generate WireGuard keys and set public key fact
  hosts: validator
  become: yes
  gather_facts: yes
  roles:
    - role: wireguard
      tasks_from: generate_keys.yml
  when: wireguard_enabled|default(false)|bool

- name: Refresh inventory and gather facts
  hosts: validator
  gather_facts: yes
  tasks:
    - meta: refresh_inventory
  when: wireguard_enabled|default(false)|bool

- name: Stage 2 - Configure peers, build config, open firewall, start service
  hosts: validator
  become: yes
  gather_facts: yes
  roles:
    - role: wireguard
      tasks_from: configure_peers.yml
  when: wireguard_enabled|default(false)|bool
